services:
  portfolio-dashboard-api:
    build:
      context: .
      args:
        SERVICE: 'main'
    ports:
      - '3000:3000'
    container_name: portfolio-dashboard-api
    depends_on:
      - db
    networks:
      - portfolio-network
    command: ['node', 'main.js']

  db:
    image: postgres:latest
    container_name: portfolio-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - portfolio-network

volumes:
  db-data:

networks:
  portfolio-network:
