Parameter:
  VPC:
    Type: "AWS::EC2::VPC::Id"
  PublicSubnet:
    Type: "AWS::EC2::Subnet::Id"
  ALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
Resources:
  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AWS::StackName}-ALB
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Type: application
      SecurityGroups:
        - !Ref LoadBalancerSG
      Subnets:
        - !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ALB

  LoadBalancerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access to the public facing load balancer
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
          FromPort: 80
          ToPort: 80

  ALBTargetGroupService1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Service1-TG
      VpcId: !Ref MyVpc
      Protocol: HTTP
      Port: 3000
      TargetType: ip

  ALBTargetGroupService2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: Service2-TG
      VpcId: !Ref MyVpc
      Protocol: HTTP
      Port: 3000
      TargetType: ip

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroupService1
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP