AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RepositoryNames:
    Type: CommaDelimitedList
    Description: List of repository names to create
  CidrBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR block
  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24
    Description: Public subnet CIDR block
  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/24
    Description: Private subnet CIDR block
  DBName:
    Type: String
    Default: "portfolio"
  DBUser:
    Type: String
    Default: "portfolio"
  DBPassword:
    Type: String
    NoEcho: true
  DBEngine:
    Type: String
    Default: "postgres"
  DBVersion:
    Type: String
    Default: "15.3"
  EnableIAMAuth:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    
Resources:
  ECRRepositories:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Sub ecr.yml
        Parameters:
          RepositoryNames: !Join
            - ','
            - !Ref RepositoryNames

  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub network.yml
    Parameters:
      CidrBlock: !Ref CidrBlock
      PublicSubnetCidr: !Ref PublicSubnetCidr
      PrivateSubnetCidr: !Ref PrivateSubnetCidr

  ECSSetup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ecs.yml
      Parameters:
        PortfolioDashboardRepositoryUri: !GetAtt ECRRepositories.Outputs.PortfolioDashboardRepositoryUri
        PortfolioApiRepositoryUri: !GetAtt ECRRepositories.Outputs.PortfolioApiRepositoryUri

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub database.yml
    Parameters:
      PortfolioVPCCidrBlock: !GetAtt Network.Outputs.VPCCidrBlock
      PortfolioPrivateSubnetId: !GetAtt Network.Outputs.PrivateSubnetId
      VPC: !GetAtt Network.Outputs.VPCId
      Subnet1: !GetAtt Network.Outputs.PrivateSubnet1Id
      Subnet2: !GetAtt Network.Outputs.PrivateSubnet2Id
      ECSSecurityGroup: !Ref ECSSetup.Outputs.ECSSecurityGroupId
      DBName: !Ref DBName
      DBUser: !Ref DBUser
      DBPassword: !Ref DBPassword
      DBEngine: !Ref DBEngine
      DBVersion: !Ref DBVersion

  
Outputs:
  RepositoryURIs:
    Description: ECR URIs for all created repositories
    Value: !GetAtt ECRRepositories.Outputs.RepositoryURIs
    Export:
      Name: !Sub ${AWS::StackName}-RepositoryURIs