name: Deploy Auth Service

on:
  push:
    paths:
      - 'apps/auth/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dashboard:
    uses: ./.github/workflows/deploy-template.yml
    with:
      APP_NAME: auth
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      REPOSITORY: devfolio/auth
