Parameters:
  ParentVPCStack:
    Type: String
    Description: "Name of the VPC stack to pull configuration from."

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AWS::StackName}-ALB
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
        - Key: routing.http2.enabled
          Value: 'true'
        # - Key: deletion_protection.enabled
        #   Value: 'false'
        # - Key: access_logs.s3.enabled
        #   Value: 'true'
        # - Key: access_logs.s3.bucket
        #   Value: !Sub '${AWS::StackName}-alb-access-logs'
        # - Key: access_logs.s3.prefix
        #   Value: !Sub '${AWS::StackName}'
      Type: application
      SecurityGroups:
        - !Ref SG
      Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-PublicSubnets'}]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ALB

  SG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Access to the public facing load balancer
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80

  ALBHttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: "404"
            ContentType: "text/plain"
            MessageBody: "Not Found"

Outputs:
  ALB:
    Description: "ALB reference."
    Value: !Ref ALB
    Export:
      Name: !Sub '${AWS::StackName}-ALB'

  ALBHttpListener:
    Description: "ALB HTTP listener reference."
    Value: !Ref ALBHttpListener
    Export:
      Name: !Sub '${AWS::StackName}-ALBHttpListener'

  # ALBUrl:
  #   Description: "ALB URL."
  #   Value: !Sub 'http://${ALB.DnsName}'
  #   Export:
  #     Name: !Sub '${AWS::StackName}-ALBUrl'

  SG:
    Description: "ALB SG reference."
    Value: !Ref SG
    Export:
      Name: !Sub '${AWS::StackName}-SG'