AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  DBInstanceIdentifier:
    Type: String
    Default: "devfolio-db"
  DBEngine:
    Type: String
    Default: "postgres"
  DBVersion:
    Type: String
    Default: "15.3"
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  EnableIAMAuth:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
  RouteTable:
    Type: String
    Default: "false"
  Subnet1Cidr:
    Type: String
    Default: 10.0.12.0/24
    Description: Private subnet CIDR block
  Subnet2Cidr:
    Type: String
    Default: 10.0.13.0/24
    Description: Private subnet CIDR block

Resources:
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet1Cidr
      VpcId: !Ref VPC
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDSSubnet1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref Subnet2Cidr
      VpcId: !Ref VPC
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref 'AWS::Region'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-RDSSubnet2

  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Sub "{{resolve:ssm:/devfolio/db-name}}"
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBVersion
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: 20
      StorageType: "gp2"
      MultiAZ: false
      PubliclyAccessible: false
      MasterUsername: !Sub "{{resolve:ssm:/devfolio/db-user}}"
      MasterUserPassword: !Sub "{{resolve:ssm-secure:/devfolio/db-password}}"
      EnableIAMDatabaseAuthentication: !Ref EnableIAMAuth
      VPCSecurityGroups:
        - !GetAtt SecurityGroup.GroupId
      DBSubnetGroupName: !Ref SubnetGroup
      BackupRetentionPeriod: 7

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for RDS PostgreSQL"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ECSSecurityGroup

  SubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2

  PrivateRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1

  PrivateRouteTableAssociationD:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2
Outputs:
  RDSPostgresEndpoint:
    Description: "PostgreSQL database endpoint"
    Value: !GetAtt DB.Endpoint.Address
